Add card payment
daplp84/agiles-grupo5-frontend pull request #12
Opened 2021-11-15 22:15 UTC by Geris

2021-11-15 22:23 UTC, daplp84 approved these changes

2021-11-16 19:01 UTC, sanchezcristian requested changes

2021-11-16 19:01 UTC, sanchezcristian commented on components/backCard.jsx
> +export default FrontCard;
No se deberia llamar BackCard?

2021-11-16 22:58 UTC, sanchezcristian approved these changes

2021-11-17 14:24 UTC, merged