show Menu list
daplp84/agiles-grupo5-frontend pull request #2
Opened 2021-09-29 02:23 UTC by Geris

2021-10-03 18:57 UTC, daplp84 approved these changes

2021-10-06 17:48 UTC, sanchezcristian requested changes
Te deje unos comentarios simples de corregir. ¡Muy buen PR!

2021-10-06 17:48 UTC, sanchezcristian commented on App.js
>          {/*<Stack.Screen name="balance" component={Balance} options={{}}>
Este código comentado lo podríamos borrar.

2021-10-10 04:54 UTC, rosanabj approved these changes
Revisado, testeado. Listo para mergear.  Se completó la primer tarea.

2021-10-10 22:40 UTC, sanchezcristian approved these changes

2021-10-10 22:41 UTC, merged